language: nix
sudo: false
cache:
  directories:
  - "$HOME/nix.store"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

env:
  global:
  - # Environment variables for BINTRAY Deployment
  - secure: AiSYr+3Zn/HGlYfG8incg1rmDPMzA/1FTBvwd/x+gqkwIHKSnb2EUXmUMaDfzNK2AQJmwaiTEK4O6WUrn2LR/37ovsigrp7AHhPVllgsifZAQAOgkvVo19Uxd7N+U6Zi1utmRWkXDPTnzC5c4/6M93AFnzhUhEd80IOYnxqiBWYZ6IyT4MHhVj4b8pje4ui/36rVi2rD3/3w1cZRwALm08rCjPyMKqa1YIbF017MlwABxH27/icMrBosZ+KBtlTIDdvXTycVOPXCJYZU/3CtpPnpFs9D959pXw/1o/nb5N5e0pnKdfxODsuhoeqIElfFWkVhNo4ns8Wajtrrqbw1+MyXXMP71xfHpwlew4zN0xCn33zleUhXzkz6mY9iN9lBjb0UwDiD+8nEisFS3GriP5RVTWe5pchSAClQzYAf3igZ4G0j/W/I1XapgZrLUq90aVzFWELIbQXkME40OnHeTOBBum0y9BCo2J6uYLHO4bMNpYnnacG9gNjOjuCA8MQOsCL+9Jxhk8kmYZB/iAqqgJi156g4KSzHCF92UKUFQG3PD30+wIPw4E3WdVXAstF5wPobYvub1HsSQnnSzGTwTuAArFOJYJczdDEnljXunS2GqWFZPFT6C1D1L7LYLaNKTJoNMrWV5fmJop+LoGPyb1BONWwDDXdPkUJUG/pKZPo=
  - secure: EJLqTv/RQANQju3U2z9p9VkMvQBYHyMkeQiwdjSsrR9DSoDc5ZMB3w3TwFBXluQ28x/ftSA7KLOyXVsxkd1oh3/OBN+NO9n3MLNIdpEcgG3Hue2tjnnaLUk7Jlp/mV44Nblcf+vjY2bKJMkR26cTWz9FwoDOwI+EuGSR820Fjp6O7f8Gb+nJfQZP/ap5zC9QD9sA3Ie1hW0hXMNfLb8s89A4Cm9I3shNmaNRzJz9wnTdvyj3d4w9AArHgldRWQg3cYUQQom+FCUsbRHuG/9ftOOxz7dUIfQPAOJ4cmegCCTM4elOWPFVQgC2me3FUdzk+nFRjw0eCxfaEUs78togKL3Sbz1OYnPA3MbDfxb7/JazoVtYSU8A05Wz3dTtAETIQGzqz2maueHeVNox/PooghrVz0PaM9mHqZJbppGQRMLe1dVNrk8QlU3NtJ6I1gn+njmsAsgl6jBAPKTSIISU7P8bZNjyoOltT1Bljf5qo7vrppwITcvwCqeMGT0JLd1x1wl9n2oYMK2QAxFFREEwLj/pa9ggExs2cVO8LPu9hZDzSG/C/HX+KemafurIqGHQDnpInyodnZLF7S/j4IC88VxnrV4NwYxxF9S6Rjm+9Mac4/NA3rXbBI3dex8YDes3yQUZFL10Wng73EyraujP55xbPzKNV/+al5cmpWAywK0=
  - # Environment variables for GITHUB
  - secure: tNFULlJt/9kS8l6lsJ4oOi5eLMXZ/L3j7FAOyPKP1fT/dw2RqtVpkAxqWyBPrWO42GNrjM7JHGr9GdfaWmnt/+x5g8qHXlKuGpeHU3VT+RqU8vmhu0f6PNiSjLliCHSNTfSkpuhvGDIYF0R9i4jPg7XmlDdFoktBrBXTR7n/Y6R4IaHKoeGRQsB5x1yc1zo3iMj9eJkPiXzWezoWo4uPpU0+bj0H72igdVCXkmlwAy2A2pBPlGZ6LAmhIJIcLey0WuVduujcXba6ulmjd4Bu2sdTT6XjRoIZESd0TzczW7VJ3Ybz2yAJdsslDDj1JdQ3O6Pqj/BO8ntOzPPVBobSx7XEibmpqrb/y3tpxa5nhEsHS4JMXTRpjkWda9BzfhvDekzqLiGuAcZUca3G78WTyztyX1ZtzvkxnCBWK9HSzrOOsPTStVArjpX6hRKR1oAt8L0hpVE1Xax/SWZUL2CnGBkhAbQorLRvIwxJnAIdOU75MUPZw5JoSRAzInEJ60jqgoRo6uJIq3U5x6D2X+/m3DoE7RxFPdPcQsapVLwxP3n6dAgk00HMS841XRKdWywNBT5+bgW5ClTpBeG1cjWN8GDYu2ugyFnFwphZ3DJmHrD8JaPmDpxUkVLBP1JS1kMoL3cByNYZGWzEk83GRrbB2Pd2wfGPzdBfcAxJ011jhW4=
  - secure: kV3Iv0XHels1ULD3l7NzUkUlobADx7z5IZ2tR67jZPUgLiNkJEKKLp88n5ESSiISRHisznNTL3hPSiEDhE41cOTAe6TGHO90BijQuHd5TRDToOf7PvHUbddLPhHiEnc4jxLxO+X4Lo+dDiDOIdgFwIyc5NOKLb/uIufqM8pXV3GrvNb4jkf6lxCjUsMbV/0CkOZEuPuHwAg/Ob4nTOlD4c4fCaQb9zo4gQ3i9JG/rqg2PW6/7+YMV4brGv8FMxpDUVgGvQy1Rz6zy0lvI38DmOGMBrqqivKxePWePxyc/jH7b/tzIRlNXV1yV9pXsLT1GtYx5H+itcN8UmipBEjpKKEEa2Bw3jAIZUxHBMmJKTFYP5yiNj54rR/VzDrrmmgdPmlQbEhPf/bNz8K5q3j72UPKH7ozn2sT0/BFnyQuVY/8A8e+UYW721L/QVqqnSYnfNuMOvAJWEHHVDS0BWu95KrRiIJyR2ii64ADz0qPNc/s1eBJHxy0KMfrejiMMG8sCOZ3Q4dyLyJ+3hiKEa5tWgS66Ye/yWClcJCOGlWqdxwArQ/LzBgFETEafGGKJODBAM7zUv5Z7HgoL4nBgJgmKrHbhRdQ2WpjD/QtH+umOaFezGZ7UBFlPMQK4/53SxYB/UMe0G0uVXLoWGZE+lCzgytiF/cRTmcJaflfgUG5tQI=
  matrix:
    - FIREFOX_VERSION="latest"
script:
  - nix-shell --command "./gradlew assemble check install"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - nix-shell --command "./.travis-publishOnRelease.sh"
